module.exports = {
  acacia_boat: { type: 'boat', texture: 'textures/entity/boat/acacia' },
  acacia_chest_boat: { type: 'boat', texture: 'textures/entity/chest_boat/acacia' },
  birch_boat: { type: 'boat', texture: 'textures/entity/boat/birch' },
  birch_chest_boat: { type: 'boat', texture: 'textures/entity/chest_boat/birch' },
  cherry_boat: { type: 'boat', texture: 'textures/entity/boat/cherry' },
  cherry_chest_boat: { type: 'boat', texture: 'textures/entity/chest_boat/cherry' },
  dark_oak_boat: { type: 'boat', texture: 'textures/entity/boat/dark_oak' },
  dark_oak_chest_boat: { type: 'boat', texture: 'textures/entity/chest_boat/dark_oak' },
  jungle_boat: { type: 'boat', texture: 'textures/entity/boat/jungle' },
  jungle_chest_boat: { type: 'boat', texture: 'textures/entity/chest_boat/jungle' },
  mangrove_boat: { type: 'boat', texture: 'textures/entity/boat/mangrove' },
  mangrove_chest_boat: { type: 'boat', texture: 'textures/entity/chest_boat/mangrove' },
  oak_boat: { type: 'boat', texture: 'textures/entity/boat/oak' },
  oak_chest_boat: { type: 'boat', texture: 'textures/entity/chest_boat/oak' },
  pale_oak_boat: { type: 'boat', texture: 'textures/entity/boat/pale_oak' },
  pale_oak_chest_boat: { type: 'boat', texture: 'textures/entity/chest_boat/pale_oak' },
  spruce_boat: { type: 'boat', texture: 'textures/entity/boat/spruce' },
  spruce_chest_boat: { type: 'boat', texture: 'textures/entity/chest_boat/spruce' },
  bamboo_raft: { type: 'boat', texture: 'textures/entity/boat/bamboo' },
  bamboo_chest_raft: { type: 'boat', texture: 'textures/entity/chest_boat/bamboo' },
  allay: { type: 'vex', texture: 'textures/entity/allay/allay' },
  armadillo: { type: 'pig', texture: 'textures/entity/armadillo' },
  axolotl: { type: 'cod', texture: 'textures/entity/axolotl/axolotl_wild' },
  bogged: { type: 'skeleton', texture: 'textures/entity/skeleton/bogged' },
  breeze: { type: 'blaze', texture: 'textures/entity/breeze/breeze' },
  breeze_wind_charge: { type: 'fireball', texture: 'textures/entity/projectiles/wind_charge' },
  camel: { type: 'horse', texture: 'textures/entity/camel/camel' },
  creaking: { type: 'enderman', texture: 'textures/entity/creaking/creaking' },
  end_crystal: { type: 'ender_pearl', texture: 'textures/entity/end_crystal/end_crystal' },
  frog: { type: 'rabbit', texture: 'textures/entity/frog/temperate_frog' },
  glow_squid: { type: 'squid', texture: 'textures/entity/squid/glow_squid' },
  goat: { type: 'sheep', texture: 'textures/entity/goat/goat' },
  happy_ghast: { type: 'ghast', texture: 'textures/entity/ghast/happy_ghast' },
  illusioner: { type: 'evoker', texture: 'textures/entity/illager/illusioner' },
  sniffer: { type: 'cow', texture: 'textures/entity/sniffer/sniffer' },
  spawner_minecart: { type: 'minecart' },
  furnace_minecart: { type: 'minecart' },
  spectral_arrow: { type: 'arrow', texture: 'textures/entity/projectiles/spectral_arrow' },
  splash_potion: { type: 'potion', texture: 'textures/items/splash_potion' },
  lingering_potion: { type: 'potion', texture: 'textures/items/lingering_potion' },
  tadpole: { type: 'cod', texture: 'textures/entity/tadpole/tadpole' },
  trader_llama: { type: 'llama' },
  warden: { type: 'iron_golem', texture: 'textures/entity/warden/warden' },
  wind_charge: { type: 'fireball', texture: 'textures/entity/projectiles/wind_charge' }
}
